<?xml version="1.0" encoding="utf-8"?><Database Name="tpcrud" Class="ProgrammingClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-OL2VBBN\SA;Initial Catalog=tpcrud;User ID=sa" SettingsObjectName="Linksql.Properties.Settings" SettingsPropertyName="tpcrudConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.productinfo_table" Member="productinfo_tables">
    <Type Name="productinfo_table">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="designation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="insertdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updatedate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="expiredate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>